server:
  port: 8081

spring:
  profiles:
    active: test
  application:
    name: wtboot

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss


logging:
  level:
    com.hgcode.wtboot: info
