spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 60
      minimum-idle: 10
    url: jdbc:mysql://127.0.0.1:3306/wtboot?&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678



mybatis-plus:
  mapper-locations: classpath:/mybatis/*.xml
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-value: 1
      logic-delete-field: is_deleted


logging:
  level:
    com.hgcode.wtboot: info
