spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
    dynamic:
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:p6spy:mysql://127.0.0.1:3306/wtboot?&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=false
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          username: root
          password: root
        slave:
          type: com.zaxxer.hikari.HikariDataSource
          url: jdbc:p6spy:mysql://127.0.0.1:3306/xxl-job?&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&useSSL=false
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          username: root
          password: root
  redis:
    host: 127.0.0.1
    port: 6379

mybatis-plus:
  mapper-locations: classpath:/config/mapper/*Mapper.xm
  global-config:
    db-config:
      id-type: id_worker
      logic-delete-value: -1



logging:
  level:
    com.hgcode.wtboot: debug

